import { SiteHeader } from "./components/SiteHeader";
import { SiteFooter } from "./components/SiteFooter";

export default function Home() {
  return (
    <div className="page">
      <SiteHeader />
      <main id="top">
        <section className="hero container-fluid"><div className="container"><div className="row align-items-center g-5"><div className="col-lg-7"><p className="eyebrow"><span /> Digital agency for the next move</p><h1>Make your brand <em>matter</em> in a crowded market.</h1><p className="heroCopy">SmTranslineInc is a digital agency helping ambitious businesses attract attention, build trust, and grow with clear strategy, creative direction, and measurable performance.</p><div className="heroActions"><a className="primaryButton" href="#contact">Start a conversation <span aria-hidden="true">↗</span></a><a className="textLink" href="#services">Explore our services <span aria-hidden="true">↓</span></a></div></div><div className="col-lg-5"><div className="heroVisual" role="img" aria-label="Creative team collaborating around a table"><div className="heroVisualTag"><span>SM / 01</span><strong>Built to be<br />remembered.</strong></div></div></div></div><div className="heroImage" role="img" aria-label="Creative team collaborating around a table" /></div></section>
        <section className="introSection container"><div className="row g-5"><div className="col-lg-4"><p className="sectionLabel">What we do</p><p className="sectionAside">One digital agency partner for the strategy, creative, code, and campaigns behind your next stage.</p></div><div className="col-lg-7 offset-lg-1"><h2>Ideas that work beautifully.</h2><p className="largeCopy">SmTranslineInc blends strategy, design, web development, and performance marketing into a single partner focused on measurable growth. We turn complex business goals into clear digital experiences people trust and remember.</p></div></div></section>
        <section id="services" className="servicesSection container-fluid"><div className="container"><div className="row justify-content-between align-items-end mb-5"><div className="col-md-6"><p className="sectionLabel">Capabilities</p><h2>Built for <em>growth.</em></h2></div><div className="col-md-4"><p className="sectionAside">A connected mix of strategy, design, development, and scalable digital campaigns.</p></div></div><div className="row g-0"><div className="serviceCard col-lg-3 col-md-6"><span>01</span><h3>Brand strategy</h3><p>Positioning, messaging, and a clear point of view that helps your business stand out.</p><a href="#contact" aria-label="Learn about brand strategy">↗</a></div><div className="serviceCard col-lg-3 col-md-6"><span>02</span><h3>Digital marketing</h3><p>Search, content, social, and campaigns built to reach the right audience and create demand.</p><a href="#contact" aria-label="Learn about digital marketing">↗</a></div><div className="serviceCard col-lg-3 col-md-6"><span>03</span><h3>Web development</h3><p>Modern websites and web experiences designed for speed, clarity, and conversion.</p><a href="#contact" aria-label="Learn about web development">↗</a></div><div className="serviceCard col-lg-3 col-md-6"><span>04</span><h3>Growth support</h3><p>Ongoing optimization, analytics, and testing to help your digital presence keep improving.</p><a href="#contact" aria-label="Learn about growth support">↗</a></div></div></div></section>
        <section id="approach" className="approachSection container"><div className="row g-5 align-items-start"><div className="col-lg-5"><p className="sectionLabel">The approach</p><h2>Clarity first.<br /><em>Then momentum.</em></h2></div><div className="col-lg-6 offset-lg-1"><div className="step"><span>01</span><div><h3>Listen closely</h3><p>We start with the real story: your audience, your ambition, and the obstacle between the two.</p></div></div><div className="step"><span>02</span><div><h3>Make it distinct</h3><p>We turn insight into a clear creative direction people can recognize, remember, and choose.</p></div></div><div className="step"><span>03</span><div><h3>Keep it moving</h3><p>We launch with purpose, learn quickly, and keep improving what matters.</p></div></div></div></div></section>
        <section id="contact" className="contactSection container-fluid"><div className="container"><div className="row align-items-end g-4"><div className="col-lg-8"><p className="eyebrow"><span /> Have a good problem?</p><h2>Let&apos;s make something <em>useful.</em></h2></div><div className="col-lg-4"><a className="contactButton" href="tel:+18445853835">Call +1 844 585 3835 <span aria-hidden="true">↗</span></a></div></div></div></section>
      </main>
      <SiteFooter />
    </div>
  );
}
